services:
  db:
    image: postgres:latest
    restart: always
    container_name: OneAI-db
    ports:
      - "${DATABASE__PORT}:5432"
    environment:
      POSTGRES_DB: ${DATABASE__DATABASE}
      POSTGRES_USER: ${DATABASE__USER}
      POSTGRES_PASSWORD: ${DATABASE__PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: OneAI_API
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE__SERVER: db
      DATABASE__PORT: ${DATABASE__PORT}
      DATABASE__USER: ${DATABASE__USER}
      DATABASE__PASSWORD: ${DATABASE__PASSWORD}
      DATABASE__DATABASE: ${DATABASE__DATABASE}
